swagger: '2.0'
info:
  version: '1.0'
  title: ApisPrueba
  contact: {}
host: localhost:3000
basePath: /dev
securityDefinitions:
  apikey:
    type: apiKey
    description: ''
    name: apikey
    in: header
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /crearPersona:
    post:
      summary: RegistrarPersona
      tags:
      - Misc
      operationId: RegistrarPersona
      deprecated: false
      produces:
      - application/json
      parameters:
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/RegistrarPersonaRequest'
      responses:
        200:
          description: ''
          headers: {}
  /obtenerPersonas:
    get:
      summary: ObtenerPersona
      tags:
      - Misc
      operationId: ObtenerPersona
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
  /llenarDynamo10x10:
    get:
      summary: LlenarPersona
      tags:
      - Misc
      operationId: LlenarPersona
      deprecated: false
      produces:
      - application/json
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
definitions:
  RegistrarPersonaRequest:
    title: RegistrarPersonaRequest
    example:
      url: www.peru.com
      editado: true
      creado: Si
      filmes: 123
      residentes: 123
      nombre: Brando
      apellidoPaterno: Saenz
      apellidoMaterno: Rojas
      edad: 11
      celular: 123456781
      distrito: SMP
    type: object
    properties:
      url:
        type: string
      editado:
        type: string
      creado:
        type: string
      filmes:
        type: string
      residentes:
        type: string
      nombre:
        type: string
      apellidoPaterno:
        type: string
      apellidoMaterno:
        type: string
      edad:
        type: string
      celular:
        type: string
      distrito:
        type: string
    required:
    - url
    - editado
    - creado
    - filmes
    - residentes
    - nombre
    - apellidoPaterno
    - apellidoMaterno
    - edad
    - celular
    - distrito
security:
- apikey: []
tags:
- name: Misc
  description: ''
